//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AssignComplaint", ReplyAction="http://tempuri.org/IService1/AssignComplaintResponse")]
        bool AssignComplaint(int complaintID, int officerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AssignComplaint", ReplyAction="http://tempuri.org/IService1/AssignComplaintResponse")]
        System.Threading.Tasks.Task<bool> AssignComplaintAsync(int complaintID, int officerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterPoliceOfficer", ReplyAction="http://tempuri.org/IService1/RegisterPoliceOfficerResponse")]
        bool RegisterPoliceOfficer(string officerName, string rank, string badgeNo, string contactNo, string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterPoliceOfficer", ReplyAction="http://tempuri.org/IService1/RegisterPoliceOfficerResponse")]
        System.Threading.Tasks.Task<bool> RegisterPoliceOfficerAsync(string officerName, string rank, string badgeNo, string contactNo, string email, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfService1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfService1.ServiceReference1.IService1>, WcfService1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AssignComplaint(int complaintID, int officerID) {
            return base.Channel.AssignComplaint(complaintID, officerID);
        }
        
        public System.Threading.Tasks.Task<bool> AssignComplaintAsync(int complaintID, int officerID) {
            return base.Channel.AssignComplaintAsync(complaintID, officerID);
        }
        
        public bool RegisterPoliceOfficer(string officerName, string rank, string badgeNo, string contactNo, string email, string username, string password) {
            return base.Channel.RegisterPoliceOfficer(officerName, rank, badgeNo, contactNo, email, username, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterPoliceOfficerAsync(string officerName, string rank, string badgeNo, string contactNo, string email, string username, string password) {
            return base.Channel.RegisterPoliceOfficerAsync(officerName, rank, badgeNo, contactNo, email, username, password);
        }
    }
}
